"""
Phase 10:
Load Dimension Tables

Flow:

stg tables
    |
    ↓
dimension tables

Surrogate keys are generated by SQL Server IDENTITY columns.
"""


from sqlalchemy import text

from python.config.database_config import get_engine



def load_categories():

    engine = get_engine()

    query = """
    INSERT INTO dim.Category
    (
        product_category_name,
        product_category_name_english
    )

    SELECT
        product_category_name,
        product_category_name_english

    FROM stg.category_translation;
    """

    with engine.begin() as conn:
        conn.execute(text(query))

    print("DimCategory loaded")



def load_customers():

    engine = get_engine()

    query = """

    INSERT INTO dim.Customer
    (
        customer_unique_id,
        customer_city,
        customer_state,
        customer_zip_code_prefix
    )

    SELECT
        customer_unique_id,
        customer_city,
        customer_state,
        customer_zip_code_prefix

    FROM stg.customers;

    """

    with engine.begin() as conn:
        conn.execute(text(query))

    print("DimCustomer loaded")



def load_sellers():

    engine = get_engine()

    query = """

    INSERT INTO dim.Seller
    (
        seller_id,
        seller_city,
        seller_state,
        seller_zip_code_prefix
    )

    SELECT
        seller_id,
        seller_city,
        seller_state,
        seller_zip_code_prefix

    FROM stg.sellers;

    """

    with engine.begin() as conn:
        conn.execute(text(query))

    print("DimSeller loaded")



def load_geography():

    engine = get_engine()

    query = """

    INSERT INTO dim.Geography
    (
        geolocation_zip_code_prefix,
        geolocation_city,
        geolocation_state,
        latitude,
        longitude
    )

    SELECT
        geolocation_zip_code_prefix,
        geolocation_city,
        geolocation_state,
        geolocation_lat,
        geolocation_lng

    FROM stg.geolocation;

    """

    with engine.begin() as conn:
        conn.execute(text(query))

    print("DimGeography loaded")



def load_products():

    engine = get_engine()

    query = """

    INSERT INTO dim.Product
    (
        product_id,
        category_key,
        product_weight_g,
        product_length_cm,
        product_height_cm,
        product_width_cm
    )

    SELECT

        p.product_id,

        c.category_key,

        p.product_weight_g,
        p.product_length_cm,
        p.product_height_cm,
        p.product_width_cm


    FROM stg.products p

    LEFT JOIN dim.Category c

    ON p.product_category_name =
       c.product_category_name;

    """

    with engine.begin() as conn:
        conn.execute(text(query))

    print("DimProduct loaded")



def load_date():

    engine = get_engine()

    query = """

    INSERT INTO dim.Date
    (
        date_key,
        full_date,
        day,
        month,
        quarter,
        year
    )

    SELECT DISTINCT

    CONVERT(
        INT,
        FORMAT(
            TRY_CONVERT(DATETIME, order_purchase_timestamp),
            'yyyyMMdd'
        )
    ),

    CAST(
        TRY_CONVERT(DATETIME, order_purchase_timestamp)
        AS DATE
    ),

    DAY(
        TRY_CONVERT(DATETIME, order_purchase_timestamp)
    ),

    MONTH(
        TRY_CONVERT(DATETIME, order_purchase_timestamp)
    ),

    DATEPART(
        QUARTER,
        TRY_CONVERT(DATETIME, order_purchase_timestamp)
    ),

    YEAR(
        TRY_CONVERT(DATETIME, order_purchase_timestamp)
    )

FROM stg.orders
WHERE TRY_CONVERT(DATETIME, order_purchase_timestamp) IS NOT NULL;

    """

    with engine.begin() as conn:
        conn.execute(text(query))

    print("DimDate loaded")




def load_dimensions():

    print("Loading dimensions...")

    load_categories()

    load_customers()

    load_sellers()

    load_geography()

    load_products()

    load_date()

    print("All dimensions loaded successfully")



if __name__ == "__main__":

    load_dimensions()